pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Clone the repository
                git 'https://github.com/Selvavignesh2/Website.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // Navigate to the sampleweb folder
                    dir('sampleweb') {
                        // Build the Docker image
                        sh 'docker build -t sampleweb-app .'
                    }
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                script {
                    // Run the Docker container, mapping port 90
                    sh 'docker run -d -p 90:80 --name sampleweb-container sampleweb-app'
                }
            }
        }
    }
    post {
        always {
            script {
                // Cleanup: Stop and remove the container
                sh 'docker stop sampleweb-container || true'
                sh 'docker rm sampleweb-container || true'
            }
        }
    }
}

